name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '17 1 * * *' # Run every day on a seemly random time.

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@7c17cb354b9a0985f2787a36dfe0e931c87405fd
    with:
      minimum-php: '7.1'
