name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '17 1 * * *' # Run every day on a seemly random time.

jobs:
  test:
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@main
    with:
      matrix.php: ${{ matrix.php }}
