name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '17 1 * * *' # Run every day on a seemly random time.

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@main
    strategy:
      matrix:
        include:
          - php: 7.1
          - php: 7.2
          - php: 7.3
          - php: 7.4
          - php: 8.0
          - php: 8.1
          - php: 8.2
          - php: 8.3
        exclude:
          - php: 5.6
          - php: 7.0
